version: '3.8'
services:
  node:
    build: .
    image: node:alpine
    ports:
      - 6300:6300
    volumes:
    networks:
      - zero-network
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - zero-network
  redisdb:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - zero-network
volumes:
  mongo-data:
    driver: local

networks:
  - zero-network:
    driver: bridge
